CURR_SWAPS = {
    "USDVND/CCS/LIBOR3M-F/1Y-SOFR": {
        "start": "0y",
        "end": "1y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6689,
    },
    "USDVND/CCS/LIBOR3M-F/2Y-SOFR": {
        "start": "0y",
        "end": "2y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6690,
    },
    "USDVND/CCS/LIBOR3M-F/3Y-SOFR": {
        "start": "0y",
        "end": "3y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6691,
    },
    "USDVND/CCS/LIBOR3M-F/4Y-SOFR": {
        "start": "0y",
        "end": "4y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6692,
    },
    "USDVND/CCS/LIBOR3M-F/5Y-SOFR": {
        "start": "0y",
        "end": "5y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6693,
    },
    "USDVND/CCS/LIBOR3M-F/7Y-SOFR": {
        "start": "0y",
        "end": "7y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6694,
    },
    "USDVND/CCS/LIBOR3M-F/10Y-SOFR": {
        "start": "0y",
        "end": "10y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6695,
    },
    "USDVND/CCS/LIBOR3M-F/15Y-SOFR": {
        "start": "0y",
        "end": "15y",
        "lock": "Pay Leg",  # Determines which legs nominal that is used as base for calculating the other leg nominal
        "nom._start": True,
        "nom._end": True,
        "receive_leg": {
            "type": "Float",
            "currency": "USD",
            "float_ref": "USD/SOFR/ON",
            "spread": 0.0,
            "day_count": "Act/360",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fix_period": True,  # If True, selected cash flow start and end days will not be business day adjusted. Cash flow pay days will not be affacted by this setting.
        },
        "pay_leg": {
            "type": "Fixed",
            "currency": "VND",
            "day_count": "Act/365",
            "pay_cal1": "United States",
            "pay_cal2": "Vietnam",
            "rolling": "3m",
            "long_stub": "None",
            "roll_conv": "None",
            "pay_offset": (0, "None"),
            "fixed_period": True,
        },
        "ins_no": 6696,
    },
}
