CURVES = {
    "ZC USD SR": {
        "curve_type": "Benchmark",
        "currency": "USD",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("rate_index", "USDSROISONZ=R"),
            ("rate_index", "USDSROIS1WZ=R"),
            ("rate_index", "USDSROIS1MZ=R"),
            ("rate_index", "USDSROIS2MZ=R"),
            ("rate_index", "USDSROIS3MZ=R"),
            ("rate_index", "USDSROIS6MZ=R"),
            ("rate_index", "USDSROIS9MZ=R"),
            ("rate_index", "USDSROIS1YZ=R"),
            ("rate_index", "USDSROIS2YZ=R"),
            ("rate_index", "USDSROIS3YZ=R"),
            ("rate_index", "USDSROIS5YZ=R"),
            ("rate_index", "USDSROIS7YZ=R"),
            ("rate_index", "USDSROIS10YZ=R"),
            ("rate_index", "USDSROIS15YZ=R"),
        ],
        "day_count": "Act/ActISDA",
    },
    "FI ZYC VND":{
        "curve_type": "Benchmark",
        "currency": "USD",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("rate_index", "3M"),
            ("rate_index", "6M"),
            ("rate_index", "9M"),
            ("rate_index", "1Y"),
            ("rate_index", "15M"),
            ("rate_index", "18M"),
            ("rate_index", "21M"),
            ("rate_index", "2Y"),
            ("rate_index", "27M"),
            ("rate_index", "30M"),
            ("rate_index", "33M"),
            ("rate_index", "3Y"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDVND_SR": {
        "curve_type": "Spread",
        "currency": "VND",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/VND/ON_FX Point"),
            ("fx_swap", "USD/VND/1W_FX Point"),
            ("fx_swap", "USD/VND/1M_FX Point"),
            ("fx_swap", "USD/VND/3M_FX Point"),
            ("fx_swap", "USD/VND/6M_FX Point"),
            ("fx_swap", "USD/VND/1Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "AUDUSD_SR": {
        "curve_type": "Spread",
        "currency": "AUD",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "AUD/USD/ON_FX Point"),
            ("fx_swap", "AUD/USD/1W_FX Point"),
            ("fx_swap", "AUD/USD/2W_FX Point"),
            ("fx_swap", "AUD/USD/3W_FX Point"),
            ("fx_swap", "AUD/USD/1M_FX Point"),
            ("fx_swap", "AUD/USD/2M_FX Point"),
            ("fx_swap", "AUD/USD/3M_FX Point"),
            ("fx_swap", "AUD/USD/4M_FX Point"),
            ("fx_swap", "AUD/USD/5M_FX Point"),
            ("fx_swap", "AUD/USD/6M_FX Point"),
            ("fx_swap", "AUD/USD/7M_FX Point"),
            ("fx_swap", "AUD/USD/8M_FX Point"),
            ("fx_swap", "AUD/USD/9M_FX Point"),
            ("fx_swap", "AUD/USD/10M_FX Point"),
            ("fx_swap", "AUD/USD/11M_FX Point"),
            ("fx_swap", "AUD/USD/1Y_FX Point"),
            ("fx_swap", "AUD/USD/15M_FX Point"),
            ("fx_swap", "AUD/USD/18M_FX Point"),
            ("fx_swap", "AUD/USD/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "EURUSD_SR": {
        "curve_type": "Spread",
        "currency": "EUR",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "EUR/USD/ON_FX Point"),
            ("fx_swap", "EUR/USD/1W_FX Point"),
            ("fx_swap", "EUR/USD/2W_FX Point"),
            ("fx_swap", "EUR/USD/3W_FX Point"),
            ("fx_swap", "EUR/USD/1M_FX Point"),
            ("fx_swap", "EUR/USD/2M_FX Point"),
            ("fx_swap", "EUR/USD/3M_FX Point"),
            ("fx_swap", "EUR/USD/4M_FX Point"),
            ("fx_swap", "EUR/USD/5M_FX Point"),
            ("fx_swap", "EUR/USD/6M_FX Point"),
            ("fx_swap", "EUR/USD/7M_FX Point"),
            ("fx_swap", "EUR/USD/8M_FX Point"),
            ("fx_swap", "EUR/USD/9M_FX Point"),
            ("fx_swap", "EUR/USD/10M_FX Point"),
            ("fx_swap", "EUR/USD/11M_FX Point"),
            ("fx_swap", "EUR/USD/1Y_FX Point"),
            ("fx_swap", "EUR/USD/15M_FX Point"),
            ("fx_swap", "EUR/USD/18M_FX Point"),
            ("fx_swap", "EUR/USD/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "GBPUSD_SR": {
        "curve_type": "Spread",
        "currency": "GBP",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "GBP/USD/ON_FX Point"),
            ("fx_swap", "GBP/USD/1W_FX Point"),
            ("fx_swap", "GBP/USD/2W_FX Point"),
            ("fx_swap", "GBP/USD/3W_FX Point"),
            ("fx_swap", "GBP/USD/1M_FX Point"),
            ("fx_swap", "GBP/USD/2M_FX Point"),
            ("fx_swap", "GBP/USD/3M_FX Point"),
            ("fx_swap", "GBP/USD/4M_FX Point"),
            ("fx_swap", "GBP/USD/5M_FX Point"),
            ("fx_swap", "GBP/USD/6M_FX Point"),
            ("fx_swap", "GBP/USD/7M_FX Point"),
            ("fx_swap", "GBP/USD/8M_FX Point"),
            ("fx_swap", "GBP/USD/9M_FX Point"),
            ("fx_swap", "GBP/USD/10M_FX Point"),
            ("fx_swap", "GBP/USD/11M_FX Point"),
            ("fx_swap", "GBP/USD/1Y_FX Point"),
            ("fx_swap", "GBP/USD/15M_FX Point"),
            ("fx_swap", "GBP/USD/18M_FX Point"),
            ("fx_swap", "GBP/USD/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDCAD_SR": {
        "curve_type": "Spread",
        "currency": "CAD",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/CAD/ON_FX Point"),
            ("fx_swap", "USD/CAD/1W_FX Point"),
            ("fx_swap", "USD/CAD/2W_FX Point"),
            ("fx_swap", "USD/CAD/3W_FX Point"),
            ("fx_swap", "USD/CAD/1M_FX Point"),
            ("fx_swap", "USD/CAD/2M_FX Point"),
            ("fx_swap", "USD/CAD/3M_FX Point"),
            ("fx_swap", "USD/CAD/4M_FX Point"),
            ("fx_swap", "USD/CAD/5M_FX Point"),
            ("fx_swap", "USD/CAD/6M_FX Point"),
            ("fx_swap", "USD/CAD/7M_FX Point"),
            ("fx_swap", "USD/CAD/8M_FX Point"),
            ("fx_swap", "USD/CAD/9M_FX Point"),
            ("fx_swap", "USD/CAD/10M_FX Point"),
            ("fx_swap", "USD/CAD/11M_FX Point"),
            ("fx_swap", "USD/CAD/1Y_FX Point"),
            ("fx_swap", "USD/CAD/15M_FX Point"),
            ("fx_swap", "USD/CAD/18M_FX Point"),
            ("fx_swap", "USD/CAD/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDCHF_SR": {
        "curve_type": "Spread",
        "currency": "CHF",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/CHF/ON_FX Point"),
            ("fx_swap", "USD/CHF/1W_FX Point"),
            ("fx_swap", "USD/CHF/2W_FX Point"),
            ("fx_swap", "USD/CHF/3W_FX Point"),
            ("fx_swap", "USD/CHF/1M_FX Point"),
            ("fx_swap", "USD/CHF/2M_FX Point"),
            ("fx_swap", "USD/CHF/3M_FX Point"),
            ("fx_swap", "USD/CHF/4M_FX Point"),
            ("fx_swap", "USD/CHF/5M_FX Point"),
            ("fx_swap", "USD/CHF/6M_FX Point"),
            ("fx_swap", "USD/CHF/7M_FX Point"),
            ("fx_swap", "USD/CHF/8M_FX Point"),
            ("fx_swap", "USD/CHF/9M_FX Point"),
            ("fx_swap", "USD/CHF/10M_FX Point"),
            ("fx_swap", "USD/CHF/11M_FX Point"),
            ("fx_swap", "USD/CHF/1Y_FX Point"),
            ("fx_swap", "USD/CHF/15M_FX Point"),
            ("fx_swap", "USD/CHF/18M_FX Point"),
            ("fx_swap", "USD/CHF/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDDKK_SR": {
        "curve_type": "Spread",
        "currency": "DKK",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/DKK/ON_FX Point"),
            ("fx_swap", "USD/DKK/1W_FX Point"),
            ("fx_swap", "USD/DKK/2W_FX Point"),
            ("fx_swap", "USD/DKK/3W_FX Point"),
            ("fx_swap", "USD/DKK/1M_FX Point"),
            ("fx_swap", "USD/DKK/2M_FX Point"),
            ("fx_swap", "USD/DKK/3M_FX Point"),
            ("fx_swap", "USD/DKK/4M_FX Point"),
            ("fx_swap", "USD/DKK/5M_FX Point"),
            ("fx_swap", "USD/DKK/6M_FX Point"),
            ("fx_swap", "USD/DKK/7M_FX Point"),
            ("fx_swap", "USD/DKK/8M_FX Point"),
            ("fx_swap", "USD/DKK/9M_FX Point"),
            ("fx_swap", "USD/DKK/10M_FX Point"),
            ("fx_swap", "USD/DKK/11M_FX Point"),
            ("fx_swap", "USD/DKK/1Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDJPY_SR": {
        "curve_type": "Spread",
        "currency": "JPY",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/JPY/ON_FX Point"),
            ("fx_swap", "USD/JPY/1W_FX Point"),
            ("fx_swap", "USD/JPY/2W_FX Point"),
            ("fx_swap", "USD/JPY/3W_FX Point"),
            ("fx_swap", "USD/JPY/1M_FX Point"),
            ("fx_swap", "USD/JPY/2M_FX Point"),
            ("fx_swap", "USD/JPY/3M_FX Point"),
            ("fx_swap", "USD/JPY/4M_FX Point"),
            ("fx_swap", "USD/JPY/5M_FX Point"),
            ("fx_swap", "USD/JPY/6M_FX Point"),
            ("fx_swap", "USD/JPY/7M_FX Point"),
            ("fx_swap", "USD/JPY/8M_FX Point"),
            ("fx_swap", "USD/JPY/9M_FX Point"),
            ("fx_swap", "USD/JPY/10M_FX Point"),
            ("fx_swap", "USD/JPY/11M_FX Point"),
            ("fx_swap", "USD/JPY/1Y_FX Point"),
            ("fx_swap", "USD/JPY/15M_FX Point"),
            ("fx_swap", "USD/JPY/18M_FX Point"),
            ("fx_swap", "USD/JPY/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDSGD_SR": {
        "curve_type": "Spread",
        "currency": "SGD",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/SGD/ON_FX Point"),
            ("fx_swap", "USD/SGD/1W_FX Point"),
            ("fx_swap", "USD/SGD/2W_FX Point"),
            ("fx_swap", "USD/SGD/3W_FX Point"),
            ("fx_swap", "USD/SGD/1M_FX Point"),
            ("fx_swap", "USD/SGD/2M_FX Point"),
            ("fx_swap", "USD/SGD/3M_FX Point"),
            ("fx_swap", "USD/SGD/4M_FX Point"),
            ("fx_swap", "USD/SGD/5M_FX Point"),
            ("fx_swap", "USD/SGD/6M_FX Point"),
            ("fx_swap", "USD/SGD/7M_FX Point"),
            ("fx_swap", "USD/SGD/8M_FX Point"),
            ("fx_swap", "USD/SGD/9M_FX Point"),
            ("fx_swap", "USD/SGD/10M_FX Point"),
            ("fx_swap", "USD/SGD/11M_FX Point"),
            ("fx_swap", "USD/SGD/1Y_FX Point"),
            ("fx_swap", "USD/SGD/15M_FX Point"),
            ("fx_swap", "USD/SGD/18M_FX Point"),
            ("fx_swap", "USD/SGD/2Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDTHB_SR": {
        "curve_type": "Spread",
        "currency": "THB",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/THB/ON_FX Point"),
            ("fx_swap", "USD/THB/1W_FX Point"),
            ("fx_swap", "USD/THB/2W_FX Point"),
            ("fx_swap", "USD/THB/1M_FX Point"),
            ("fx_swap", "USD/THB/2M_FX Point"),
            ("fx_swap", "USD/THB/3M_FX Point"),
            ("fx_swap", "USD/THB/6M_FX Point"),
            ("fx_swap", "USD/THB/9M_FX Point"),
            ("fx_swap", "USD/THB/1Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDCNY_SR": {
        "curve_type": "Spread",
        "currency": "CNY",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/CNY/ON_FX Point"),
            ("fx_swap", "USD/CNY/1W_FX Point"),
            ("fx_swap", "USD/CNY/2W_FX Point"),
            ("fx_swap", "USD/CNY/3W_FX Point"),
            ("fx_swap", "USD/CNY/1M_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDHKD_SR": {
        "curve_type": "Spread",
        "currency": "HKD",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/HKD/ON_FX Point"),
            ("fx_swap", "USD/HKD/1W_FX Point"),
            ("fx_swap", "USD/HKD/2W_FX Point"),
            ("fx_swap", "USD/HKD/3W_FX Point"),
            ("fx_swap", "USD/HKD/1M_FX Point"),
            ("fx_swap", "USD/HKD/2M_FX Point"),
            ("fx_swap", "USD/HKD/3M_FX Point"),
            ("fx_swap", "USD/HKD/4M_FX Point"),
            ("fx_swap", "USD/HKD/5M_FX Point"),
            ("fx_swap", "USD/HKD/6M_FX Point"),
            ("fx_swap", "USD/HKD/7M_FX Point"),
            ("fx_swap", "USD/HKD/8M_FX Point"),
            ("fx_swap", "USD/HKD/9M_FX Point"),
            ("fx_swap", "USD/HKD/10M_FX Point"),
            ("fx_swap", "USD/HKD/11M_FX Point"),
            ("fx_swap", "USD/HKD/1Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDNOK_SR": {
        "curve_type": "Spread",
        "currency": "NOK",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/NOK/ON_FX Point"),
            ("fx_swap", "USD/NOK/1W_FX Point"),
            ("fx_swap", "USD/NOK/2W_FX Point"),
            ("fx_swap", "USD/NOK/3W_FX Point"),
            ("fx_swap", "USD/NOK/1M_FX Point"),
            ("fx_swap", "USD/NOK/2M_FX Point"),
            ("fx_swap", "USD/NOK/3M_FX Point"),
            ("fx_swap", "USD/NOK/4M_FX Point"),
            ("fx_swap", "USD/NOK/5M_FX Point"),
            ("fx_swap", "USD/NOK/6M_FX Point"),
            ("fx_swap", "USD/NOK/7M_FX Point"),
            ("fx_swap", "USD/NOK/8M_FX Point"),
            ("fx_swap", "USD/NOK/9M_FX Point"),
            ("fx_swap", "USD/NOK/10M_FX Point"),
            ("fx_swap", "USD/NOK/11M_FX Point"),
            ("fx_swap", "USD/NOK/1Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDSEK_SR": {
        "curve_type": "Spread",
        "currency": "SEK",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/SEK/ON_FX Point"),
            ("fx_swap", "USD/SEK/SW_FX Point"),
            ("fx_swap", "USD/SEK/2W_FX Point"),
            ("fx_swap", "USD/SEK/3W_FX Point"),
            ("fx_swap", "USD/SEK/1M_FX Point"),
            ("fx_swap", "USD/SEK/2M_FX Point"),
            ("fx_swap", "USD/SEK/3M_FX Point"),
            ("fx_swap", "USD/SEK/4M_FX Point"),
            ("fx_swap", "USD/SEK/5M_FX Point"),
            ("fx_swap", "USD/SEK/6M_FX Point"),
            ("fx_swap", "USD/SEK/7M_FX Point"),
            ("fx_swap", "USD/SEK/8M_FX Point"),
            ("fx_swap", "USD/SEK/9M_FX Point"),
            ("fx_swap", "USD/SEK/10M_FX Point"),
            ("fx_swap", "USD/SEK/11M_FX Point"),
            ("fx_swap", "USD/SEK/1Y_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDKRW_SR": {
        "curve_type": "Spread",
        "currency": "KRW",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/KRW/ON_FX Point"),
            ("fx_swap", "USD/KRW/1W_FX Point"),
            ("fx_swap", "USD/KRW/1M_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDINR_SR": {
        "curve_type": "Spread",
        "currency": "INR",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/INR/ON_FX Point"),
            ("fx_swap", "USD/INR/1W_FX Point"),
            ("fx_swap", "USD/INR/1M_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDKWD_SR": {
        "curve_type": "Spread",
        "currency": "KWD",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/KWD/ON_FX Point"),
            ("fx_swap", "USD/KWD/1W_FX Point"),
            ("fx_swap", "USD/KWD/1M_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDRUB_SR": {
        "curve_type": "Spread",
        "currency": "RUB",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/RUB/ON_FX Point"),
            ("fx_swap", "USD/RUB/1W_FX Point"),
            ("fx_swap", "USD/RUB/2W_FX Point"),
            ("fx_swap", "USD/RUB/3W_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "USDSAR_SR": {
        "curve_type": "Spread",
        "currency": "SAR",
        "base_curve": "ZC USD SR",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/SAR/ON_FX Point"),
            ("fx_swap", "USD/SAR/1W_FX Point"),
            ("fx_swap", "USD/SAR/1M_FX Point"),
        ],
        "day_count": "Act/ActISDA",
    },
    "ZC VND CCS SR": {
        "curve_type": "Benchmark",
        "currency": "VND",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("fx_swap", "USD/VND/ON_FX Point"),
            ("fx_swap", "USD/VND/1W_FX Point"),
            ("fx_swap", "USD/VND/1M_FX Point"),
            ("fx_swap", "USD/VND/3M_FX Point"),
            ("fx_swap", "USD/VND/6M_FX Point"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/1Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/2Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/3Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/4Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/5Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/7Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/10Y-SOFR"),
            ("curr_swap", "USDVND/CCS/LIBOR3M-F/15Y-SOFR"),
        ],
        "dependency_curve": "ZC USD SR",
        "day_count": "Act/ActISDA",
    },
}
