CURVES = {
    "ZC USD SR": {
        "curve_type": "Benchmark",
        "currency": "USD",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("rate_index", "USDSROISONZ=R"),
            ("rate_index", "USDSROIS1WZ=R"),
            ("rate_index", "USDSROIS1MZ=R"),
            ("rate_index", "USDSROIS2MZ=R"),
            ("rate_index", "USDSROIS3MZ=R"),
            ("rate_index", "USDSROIS6MZ=R"),
            ("rate_index", "USDSROIS9MZ=R"),
            ("rate_index", "USDSROIS1YZ=R"),
            ("rate_index", "USDSROIS2YZ=R"),
            ("rate_index", "USDSROIS3YZ=R"),
            ("rate_index", "USDSROIS5YZ=R"),
            ("rate_index", "USDSROIS7YZ=R"),
            ("rate_index", "USDSROIS10YZ=R"),
            ("rate_index", "USDSROIS15YZ=R"),
        ],
        "day_count": "Act/ActISDA",
    },
    "FI ZYC VND":{
        "curve_type": "Benchmark",
        "currency": "USD",
        "interpolation": "Linear",
        "interpol_rate_type": "Spot Rate",
        "extrapol_short_end": "Default",
        "extrapol_long_end": "Default",
        "benchmarks": [
            ("rate_index", "3M"),
            ("rate_index", "6M"),
            ("rate_index", "9M"),
            ("rate_index", "1Y"),
            ("rate_index", "15M"),
            ("rate_index", "18M"),
            ("rate_index", "21M"),
            ("rate_index", "2Y"),
            ("rate_index", "27M"),
            ("rate_index", "30M"),
            ("rate_index", "33M"),
            ("rate_index", "3Y"),
            ("rate_index", "5Y"),
            ("rate_index", "7Y"),
            ("rate_index", "10Y"),
            ("rate_index", "15Y"),
            ("rate_index", "20Y"),
            ("rate_index", "30Y"),
        ],
        "day_count": "Act/ActISDA",
    },
}
