FX_SWAPS = {
    "USD/VND/ON_FX Point": {
        "currency1": "USD",
        "currency2": "VND",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2454,
    },
    "USD/VND/1W_FX Point": {
        "currency1": "USD",
        "currency2": "VND",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2442,
    },
    "USD/VND/1M_FX Point": {
        "currency1": "USD",
        "currency2": "VND",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2441,
    },
    "USD/VND/3M_FX Point": {
        "currency1": "USD",
        "currency2": "VND",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2446,
    },
    "USD/VND/6M_FX Point": {
        "currency1": "USD",
        "currency2": "VND",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2450,
    },
    "USD/VND/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "VND",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2443,
    },
    "AUD/USD/ON_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 1,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/1W_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 2,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/2W_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 3,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/3W_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 4,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/1M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 5,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/2M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 6,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/3M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 7,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/4M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 8,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/5M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 9,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/6M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 10,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/7M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 11,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/8M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 12,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/9M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 13,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/10M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 14,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/11M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 15,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/1Y_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 16,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/15M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 17,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/18M_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 18,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "AUD/USD/2Y_FX Point": {
        "currency1": "AUD",
        "currency2": "USD",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 19,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/ON_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 17,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/1W_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 18,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/2W_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 19,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/3W_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 20,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/1M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 21,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/2M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 22,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/3M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 23,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/4M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 24,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/5M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 25,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/6M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 26,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/7M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 27,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/8M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 28,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/9M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 29,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/10M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 30,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/11M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 31,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/1Y_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 32,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/15M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 33,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/18M_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 34,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "EUR/USD/2Y_FX Point": {
        "currency1": "EUR",
        "currency2": "USD",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 35,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/ON_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 33,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/1W_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 34,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/2W_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 35,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/3W_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 36,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/1M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 37,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/2M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 38,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/3M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 39,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/4M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 40,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/5M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 41,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/6M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 42,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/7M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 43,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/8M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 44,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/9M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 45,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/10M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 46,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/11M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 47,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/1Y_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 48,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/15M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 49,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/18M_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 50,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "GBP/USD/2Y_FX Point": {
        "currency1": "GBP",
        "currency2": "USD",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 51,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/ON_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 49,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/1W_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 50,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/2W_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 51,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/3W_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 52,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/1M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 53,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/2M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 54,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/3M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 55,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/4M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 56,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/5M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 57,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/6M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 58,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/7M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 59,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/8M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 60,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/9M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 61,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/10M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 62,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/11M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 63,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 64,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/15M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 65,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/18M_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 66,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CAD/2Y_FX Point": {
        "currency1": "USD",
        "currency2": "CAD",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 67,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/ON_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 65,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/1W_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 66,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/2W_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 67,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/3W_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 68,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/1M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 69,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/2M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 70,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/3M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 71,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/4M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 72,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/5M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 73,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/6M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 74,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/7M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 75,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/8M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 76,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/9M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 77,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/10M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 78,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/11M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 79,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 80,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/15M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 81,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/18M_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 82,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CHF/2Y_FX Point": {
        "currency1": "USD",
        "currency2": "CHF",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 83,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CNY/ON_FX Point": {
        "currency1": "USD",
        "currency2": "CNY",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 81,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CNY/1W_FX Point": {
        "currency1": "USD",
        "currency2": "CNY",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 82,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CNY/2W_FX Point": {
        "currency1": "USD",
        "currency2": "CNY",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 83,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CNY/3W_FX Point": {
        "currency1": "USD",
        "currency2": "CNY",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 84,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/CNY/1M_FX Point": {
        "currency1": "USD",
        "currency2": "CNY",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 85,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/ON_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 97,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/1W_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 98,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/2W_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 99,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/3W_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 100,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/1M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 101,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/2M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 102,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/3M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 103,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/4M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 104,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/5M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 105,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/6M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 106,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/7M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 107,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/8M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 108,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/9M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 109,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/10M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 110,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/11M_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 111,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/DKK/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "DKK",
        "start": "0y",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 112,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/ON_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 113,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/1W_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 114,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/2W_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 115,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/3W_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 116,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/1M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 117,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/2M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 118,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/3M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 119,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/4M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 120,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/5M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 121,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/6M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 122,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/7M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 123,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/8M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 124,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/9M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 125,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/10M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 126,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/11M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 127,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0y",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 128,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/15M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 129,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/18M_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 130,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/JPY/2Y_FX Point": {
        "currency1": "USD",
        "currency2": "JPY",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 131,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/ON_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 132,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/1W_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 133,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/2W_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 115,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/3W_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 116,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/1M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 117,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/2M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 118,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/3M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 119,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/4M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 120,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/5M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 121,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/6M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 122,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/7M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 123,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/8M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 124,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/9M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 125,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/10M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 126,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/11M_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 127,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/HKD/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "HKD",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 128,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/INR/ON_FX Point": {
        "currency1": "USD",
        "currency2": "INR",
        "start": "0y",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 129,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/INR/1W_FX Point": {
        "currency1": "USD",
        "currency2": "INR",
        "start": "0y",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 130,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/INR/1M_FX Point": {
        "currency1": "USD",
        "currency2": "INR",
        "start": "0y",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 133,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/KRW/ON_FX Point": {
        "currency1": "USD",
        "currency2": "KRW",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 145,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/KRW/1W_FX Point": {
        "currency1": "USD",
        "currency2": "KRW",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 146,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/KRW/1M_FX Point": {
        "currency1": "USD",
        "currency2": "KRW",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 149,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/KWD/ON_FX Point": {
        "currency1": "USD",
        "currency2": "KWD",
        "start": "0y",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 161,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/KWD/1W_FX Point": {
        "currency1": "USD",
        "currency2": "KWD",
        "start": "0y",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 162,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/KWD/1M_FX Point": {
        "currency1": "USD",
        "currency2": "KWD",
        "start": "0y",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 165,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/ON_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 177,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/1W_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 178,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/2W_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 179,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/3W_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 180,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/1M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 181,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/2M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 182,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/3M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 183,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/4M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 184,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/5M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 185,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/6M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 186,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/7M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 187,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/8M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 188,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/9M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 189,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/10M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 190,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/11M_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 191,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/NOK/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "NOK",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 192,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/RUB/ON_FX Point": {
        "currency1": "USD",
        "currency2": "RUB",
        "start": "0y",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 193,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/RUB/1W_FX Point": {
        "currency1": "USD",
        "currency2": "RUB",
        "start": "0y",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 194,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/RUB/2W_FX Point": {
        "currency1": "USD",
        "currency2": "RUB",
        "start": "0y",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 195,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/RUB/3W_FX Point": {
        "currency1": "USD",
        "currency2": "RUB",
        "start": "0y",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 196,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SAR/ON_FX Point": {
        "currency1": "USD",
        "currency2": "SAR",
        "start": "0y",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 209,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SAR/1W_FX Point": {
        "currency1": "USD",
        "currency2": "SAR",
        "start": "0y",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 210,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SAR/1M_FX Point": {
        "currency1": "USD",
        "currency2": "SAR",
        "start": "0y",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 213,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/ON_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 225,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/SW_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 226,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/2W_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 227,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/3W_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 228,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/1M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 229,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/2M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 230,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/3M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 231,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/4M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 232,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/5M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 233,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/6M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 234,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/7M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 235,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/8M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 236,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/9M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 237,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/10M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 238,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/11M_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 239,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SEK/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "SEK",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 240,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/ON_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 241,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/1W_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 242,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/2W_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 243,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/3W_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "3w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 244,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/1M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 245,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/2M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 246,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/3M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 247,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/4M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "4m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 248,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/5M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "5m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 249,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/6M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 250,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/7M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "7m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 251,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/8M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "8m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 252,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/9M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 253,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/10M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "10m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 254,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/11M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "11m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 255,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 256,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/15M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0y",
        "end": "15m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 257,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/18M_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0y",
        "end": "18m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 258,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/SGD/2Y_FX Point": {
        "currency1": "USD",
        "currency2": "SGD",
        "start": "0y",
        "end": "2y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 259,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/ON_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "1d",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 257,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/1W_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "1w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 258,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/2W_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "2w",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 259,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/1M_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "1m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 261,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/2M_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "2m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 262,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/3M_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "3m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 263,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/6M_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "6m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 266,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/9M_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "9m",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 269,  # Note: Placeholder ins_no, to be updated accordingly
    },
    "USD/THB/1Y_FX Point": {
        "currency1": "USD",
        "currency2": "THB",
        "start": "0d",
        "end": "1y",
        "pay_method": "Following",
        "roll_conv": "Preserve EOM",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "ignore_pay_cal": "Start",
        "ins_no": 272,  # Note: Placeholder ins_no, to be updated accordingly
    },
}
