RATE_INDEX = {
    "USDSROISONZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "1d",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "roll_conv": "None",
        "rate_type": "annual",
        "day_method": "Following",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2492,
    },
    "USDSROIS1WZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "1w",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "roll_conv": "None",
        "rate_type": "annual",
        "day_method": "Following",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2482,
    },
    "USDSROIS1MZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "1m",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2481,
    },
    "USDSROIS2MZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "2m",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2484,
    },
    "USDSROIS3MZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "3m",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2486,
    },
    "USDSROIS6MZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "6m",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2489,
    },
    "USDSROIS9MZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "9m",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2491,
    },
    "USDSROIS1YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "1y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2483,
    },
    "USDSROIS2YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "2y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2485,
    },
    "USDSROIS3YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "3y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2487,
    },
    "USDSROIS5YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "5y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2488,
    },
    "USDSROIS7YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "7y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2490,
    },
    "USDSROIS10YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "10y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2479,
    },
    "USDSROIS15YZ=R": {
        "currency": "USD",
        "start_period": "0d",
        "end_period": "15y",
        "pay_cal": "United States",
        "day_count": "Act/ActISMA",
        "rate_type": "annual",
        "day_method": "Mod. Following",
        "roll_conv": "EOM Cal Days",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2480,
    },
    "3M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "3m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2481,   
    },
    "6M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "6m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2482,   
    },
    "9M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "9m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2483,   
    },
    "1Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "1y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2484,   
    },
    "15M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "15m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2485,   
    },
    "18M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "18m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2486,   
    },
    "21M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "21m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2487,   
    },
    "2Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "2y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2488,   
    },
    "27M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "27m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2489,   
    },
    "30M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "30m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2490,   
    },
    "33M": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "33m",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2491,   
    },
    "3Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "3y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2492,   
    },
    "5Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "5y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2493,   
    },
    "7Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "7y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2494,   
    },
    "10Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "10y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2495,   
    },
    "15Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "15y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2496,   
    },
    "20Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "20y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2497,   
    },
    "30Y": {
        "currency": "VND",
        "start_period": "0d",
        "end_period": "30y",
        "pay_cal": "VND",
        "day_count": "Act/365",
        "rate_type": "annual",
        "day_method": "Following",
        "roll_conv": "None",
        "quotation": "Coupon",
        "spot_days": 0,
        "settle_calendar": "VAS Accounting VN",
        "start_adjustment": "None",
        "ignore_pay_cal": "Start",
        "ins_no": 2498,   
    },
}
